apiVersion: v1
kind: Namespace
metadata:
  name: my-argo-managed-namespace
  labels:
    name: my-argo-managed-namespace
    argocd.argoproj.io/managed-by: "true"
    argocd.argoproj.io/sync-options: "Prune=false"
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-status: "Synced"
    argocd.argoproj.io/sync-revision: "HEAD"
    argocd.argoproj.io/sync-source: "https://github.com/DexRoku/Terraform-Study/tree/main/terraform-study/k8s-manifests"
    argocd.argoproj.io/sync-target: "https://github.com/DexRoku/Terraform-Study/tree/main/terraform-study/k8s-manifests"