apiVersion: v1
kind: Namespace
metadata:
  name: my-argo-managed-namespace
  labels:
    # You can keep this label if you want:
    name: my-argo-managed-namespace
  annotations:
    # These annotations instruct Argo CD how to handle this resource
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/resource-ignore: |
      jsonPointers:
      - /metadata/labels/argocd.argoproj.io~1sync-options
      - /metadata/labels/argocd.argoproj.io~1sync-source
      - /metadata/labels/argocd.argoproj.io~1sync-target
      - /metadata/labels/argocd.argoproj.io~1instance
      - /metadata/labels/argocd.argoproj.io~1managed-by-application
      - /metadata/labels/argocd.argoproj.io~1managed-by
      - /metadata/labels/argocd.argoproj.io~1sync-revision
      - /metadata/labels/argocd.argoproj.io~1sync-status